baseURL = "http://austingebauer.com/"
languageCode = "en-us"
title = "austingebauer"
theme = "ag"
relativeURLs = true
enableEmoji = true
googleAnalytics = "UA-150288366-2"

# Use syntax highlighting of the theme
pygmentsUseClasses = false
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsStyle = "borland"
pygmentsOptions = "linenos=table"

# Defines menu items for the theme
[menu]
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 110

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 120
