baseURL = "https://example.com"
title = "Your Website Title"
languageCode = "en-us"
theme = "devise"
relativeURLs = true
enableEmoji = true
googleAnalytics = ""
enableRobotsTXT = true
copyright = "&copy; Copyright Year, Your Name"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    title = "About"
    url = "/about/"
    weight = -110

  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    title = "Posts"
    url = "/post/"
    weight = -100

  [[menu.main]]
    identifier = "categories"
    name = "Categories"
    title = "Categories"
    url = "/categories/"
    weight = -90

[params]
  header_title = "Your Name"
  header_subtitle = "Your Creative Subtitle"
  home_image = "/images/avatar.png"
  recent_posts = 5
  mainSections = ["posts", "post", "blog"]
  [[params.social]]
    fa_icon = "fab fa-github fa-1x"
    href = ""
  [[params.social]]
  	fa_icon = "fab fa-linkedin-in fa-1x"
  	href = ""
  [[params.social]]
  	fa_icon = "fab fa-twitter fa-1x"
  	href = ""
  [[params.social]]
  	fa_icon = "fas fa-at fa-1x"
  	href = ""
